name: Build and Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      BUCKET_CAPACITY: 1
      BUCKET_REFILL_AMOUNT: 1
      BUCKET_REFILL_TIME_MINUTES: 1
      OPENAI_API_KEY: aaaaaaaaa
      TMDB_KEY: aaaaaaaaa
      USE_WEB_SEARCH: false


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Run tests
        run: mvn test

      - name: Build jar
        run: mvn clean package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mavirgil/more-like-backend:latest
            ghcr.io/mavirgil/more-like-backend:${{ github.sha }}

      - name: Trigger Coolify deploy
        run: |
          curl -X GET "${{ secrets.COOLIFY_DEPLOY_WEBHOOK }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"